### ISSUE TITLE
Can't Build Mercury Browser

### ISSUE THREAD

**Issue by iamevilmonarch** [Alex313031/Mercury#33]
I am building mercury v115.1.0 in void linux and by following the instructions in mercury docs I need to ask is what do you mean by firefox repo cause i have followed two methods trying to install mercury browser 

      1.  i placed my  own firefox repo from /usr/lib/firefox/ to ~/mozilla-unified
       2. i downloaded source code from firefox and placed in ~/mozilla-unified
       by trying both ways it is giving the following error

    Script to Rebase/Sync Mozilla repo on Linux._

    Rebasing/Syncing with mozilla-unified Mercurial repository... ./trunk.sh: line 40: hg: command not found

    can you please look into this issue and guide me

**Comment by iamevilmonarch** [comment]
okay after many trials and error i found a way to install mercury browser and what was needed.i was able to install mercury browser by going on mozilla firefox site and installing mercurial,I followed your doc and I successfully ran bootstrap.sh,trunk.sh,setup.sh but when i run build.sh i run into the following problems 


_4:04.54 make[3]: *** [/home/popeye/mozilla-unified/config/recurse.mk:72: build/clang-plugin/host-objects] Error 2
 4:04.60 make[3]: Leaving directory '/home/popeye/mozilla-unified/obj-x86_64-pc-linux-gnu/instrumented'
 4:04.61 make[2]: *** [/home/popeye/mozilla-unified/config/recurse.mk:34: compile] Error 2
 4:04.65 make[2]: Leaving directory '/home/popeye/mozilla-unified/obj-x86_64-pc-linux-gnu/instrumented'
 4:04.66 make[1]: *** [/home/popeye/mozilla-unified/config/rules.mk:361: default] Error 2
 4:04.70 make[1]: Leaving directory '/home/popeye/mozilla-unified/obj-x86_64-pc-linux-gnu/instrumented'
 4:04.72 make: *** [client.mk:60: build] Error 2
 4:04.80 W 0 compiler warnings present._

 I cannot seem to figure what is this Error 2 can you help me with this or can you point in some direction which i can follow

**Comment by Alex313031** [comment]
@iamevilmonarch You should use hg to clone the firefox repository in $HOME, by following the steps in Mozillas documentation.

Then, you should clone the mercury repo also to $HOME, and run `./trunk.sh`, then `./setup.sh`.

Finally, you should copy the mozconfig that is relevant for the platform. Since you are on linux, you would just copy this > https://github.com/Alex313031/Mercury/blob/main/mozconfig into mozilla-unified (the root of the mozilla repo).

Then, you can either run the `./build.sh` script in mercury, or cd to the mozilla repo and run `./mach bootstrap` and `./mach build`. You can use `./mach build -v` to show verbose stuff.

However, since Void is not a "supported" build host, and it seems you are getting clang plugin errors, you should try commenting out this line > https://github.com/Alex313031/Mercury/blob/main/mozconfig#L22
