### ISSUE TITLE
MPEG-DASH and HEVC/H.265 support

### ISSUE THREAD

**Issue by trimechee** [Alex313031/Mercury#34]
Hello, for more smooth playback, we hope that these features are enabled in our beloved Mercury Browser please ? or may be it is good idea to add option to enable these flags manually....

Experimental MPEG-DASH support

and

HEVC/H.265 support on  Windows 

Thank you !

**Comment by trimechee** [comment]
@Alex313031 @gz83  I'm really very surprised, I tested this link with firefox browser

https://web.archive.org/web/20230319103654/http://h265.webmfiles.org/embed-h265-video.php

and firefox can't play hevc videos !! I'm surprised that a big famous company like Mozilla didn't get license for hevc codec?!! is there a way to add hevc codec to firefox and our beloved Mercury borwser please ?

**Comment by gz83** [comment]
If the Mercury browser cannot play the video you mentioned, it may be that the upstream Firefox browser lacks the corresponding codec, but the upstream Firefox browser also uses the ffmpeg component, which should be able to perform the most basic software codec for the video , you can use the Firefox browser that is consistent with the Mercury version for testing.

Regarding the hevc issue in the Firefox browser, because no developer has contributed code related to hevc to the Firefox browser for the time being, the Firefox browser and its related derivative versions may not be able to play normally or encode and decode videos that use the Hevc technology. Need to wait for developers to implement related functions in Firefox browser. In addition, Mozilla's attitude towards hevc and its living environment are also different from Google's. There are many other factors involved here, so I won't mention them one by one here.

By the way, I will provide you with a discussion about hevc on bugzilla:
https://bugzilla.mozilla.org/show_bug.cgi?id=1332136

Finally, since I am not very familiar with and good at dealing with the code of the media module, I am temporarily unable to significantly modify the media module of the Firefox browser to implement hevc. If you need assistance with other aspects, such as JPEG-XL support,  the blink engine of Chrome/Chromium, the content module of Chrome/Chromium, the tabstrip of Chrome/Chromium, etc., please feel free to initiate  issue in the corresponding repo for consultation.

@trimechee

**Comment by trimechee** [comment]
Ohh very very interesting !! Thank you so much for these precious informations @gz83 :) 🥇 💯

**Comment by trimechee** [comment]
Hello, @Alex313031 @gz83 it seems that Waterfox  support HEVC , it will be awesome to add hevc, thank you :)
 it seems it is very important to have support of hevc : 
"a lot of these videos nowaday is above 5.2 and we simply can't view them unless download, or use chrome, or force upgrade to windows 10. " 


Waterfox Classic and Waterfox Current support for Advanced Video Coding (H.264) and High Efficiency Video Coding (HEVC) (H.265)  

https://www.reddit.com/r/waterfox/comments/dqnkvq/waterfox_classic_and_waterfox_current_support_for/


https://www.reddit.com/r/waterfox/comments/dq6i2w/can_waterfox_support_h264_above_level_51/

**Comment by gz83** [comment]
> Hello, @Alex313031 @gz83 it seems that Waterfox support HEVC , it will be awesome to add hevc, thank you :) it seems it is very important to have support of hevc : "a lot of these videos nowaday is above 5.2 and we simply can't view them unless download, or use chrome, or force upgrade to windows 10. "
> 
> Waterfox Classic and Waterfox Current support for Advanced Video Coding (H.264) and High Efficiency Video Coding (HEVC) (H.265)
> 
> [reddit.com/r/waterfox/comments/dqnkvq/waterfox_classic_and_waterfox_current_support_for](https://www.reddit.com/r/waterfox/comments/dqnkvq/waterfox_classic_and_waterfox_current_support_for/)
> 
> [reddit.com/r/waterfox/comments/dq6i2w/can_waterfox_support_h264_above_level_51](https://www.reddit.com/r/waterfox/comments/dq6i2w/can_waterfox_support_h264_above_level_51/)

Sorry, the content of the webpage you provided is many years old, so we may not be able to fully rely on the information provided. Also, are you currently using waterfox? Can it play videos that require MPEG-DASH or HEVC/H.265?

@trimechee

**Comment by trimechee** [comment]
Hello @gz83 , there is no problem, thank you :) thr only problem is my graphic card is frrom year 2017 and doesn"t support natively hardware acceleration AV1 codec and software decode of AV1 consumes may energy..... I asked Mr Alex94 the developer of Waterfox about hevc and he answered me this response : 

"Unfortunately, it's not really feasible both from a technical or financial perspective.

For the former, I just don't have the technical expertise for it, and it would be a massive project to take on.

For the latter, there are lots of licensing issues with MPEG-DASH and H265 - which makes it quite expensive to license overall.

It's sad, but the reason why codecs such as AV1 have come about to compete with them."
