### ISSUE TITLE
Wrong linux release uploaded

### ISSUE THREAD

**Issue by sandboiii** [Alex313031/Mercury#48]
Hey, looks like you uploaded the wrong linux build for 115.4.0 
![image](https://github.com/Alex313031/Mercury/assets/17468894/14b1402a-97aa-467c-ab7b-3e20c3112067)

**Comment by Alex313031** [comment]
@sandboiii Oops, you are right. I have a folder called "releases" in my local clone of the repo, (which is in the .gitignore file), and I have kept all my releases in there. Must've made a mistake. I'm just gonna clear out that folder so it doesn't happen again, because it's not like I need to archive them since there is already an archive on here.

**Comment by Alex313031** [comment]
@sandboiii Fixed!

**Comment by sandboiii** [comment]
Thank you!

**Comment by sandboiii** [comment]
Oh, wait. There is one more problem. There is a directory with the old version in name inside the zip archive. 
![image](https://github.com/Alex313031/Mercury/assets/17468894/9daedca3-2ca1-407f-86a6-71ae5b4b74a0)

**Comment by sandboiii** [comment]
Thanks!
