### ISSUE TITLE
[Feature Request] Post-Link Optimizations (BOLT, Propeller)

### ISSUE THREAD

**Issue by AndreVallestero** [Alex313031/Mercury#52]
I didn't notice any mention of these optimization techniques in the docs. Could we also apply them to squeeze out a few percentage points of performance? From what I've seen, BOLT can improve performance by 3% for binaries already optimized with PGO and LTO.

**Comment by gz83** [comment]
Mercury has now introduced appropriate optimization parameters, but unfortunately, due to Firefox's infrastructure limitations, the optimization parameters cannot be applied to all code and components, and at the same time, using more advanced optimization techniques in Firefox's code and components may face the same problem.

@AndreVallestero
