### ISSUE TITLE
Can't make Mercury not open my past session tabs on restart 

### ISSUE THREAD

**Issue by fuckindumbfox** [Alex313031/Mercury#63]
Pretty self explanatory or am I missing something here? I'm pretty new to submitting issues, idk what i should put here so sorry if i miss something.
I'm using Mercury ver. 115.4.0esr (64-bit) on Windows 11 Pro

**Comment by falcie1337** [comment]
This is because Mercury forks from other Firefox forks, and one of them includes Librewolf (a privacy hardening fork of Firefox), you can solve this by going into about:config and searching for privacy.clearOnShutdown and toggling what you want to keep after you close your browser, the one specifically for tabs is privacy.clearOnShutdown.history, hope this helps.
