### ISSUE TITLE
Any idea of supporting macos? Thanks. 

### ISSUE THREAD

**Issue by tomobs** [Alex313031/Mercury#85]

**Comment by j03ll0b0** [comment]
Hello Mercury under mac... sorta...
![Screenshot 2024-01-14 at 12 21 55 AM](https://github.com/Alex313031/Mercury/assets/104862685/a7672447-4c8c-43a1-b3bc-358cdebb9830)

**Comment by tomobs** [comment]
Holly *, thanks!

**Comment by tomobs** [comment]
But how do you install it.

**Comment by j03ll0b0** [comment]
I got it working by using docker and XQuartz, I’ll reply later with the whole procedure, it’s rather fun and it actually works with webgl and everything, quite a hack since there is not yet a native one for Mac, if you want audio is also a procedure to get pulse working on Mac first and then routing the audio, but nevertheless also works just fine, don’t expect a launcher app on Mac for this, or at least I haven’t tried so I can’t tell yet whether it can be done or not.

**Comment by j03ll0b0** [comment]
here it is:

https://www.youtube.com/watch?v=cNDR6Z24KLM

https://gist.github.com/paul-krohn/e45f96181b1cf5e536325d1bdee6c949

https://copyprogramming.com/howto/running-gui-from-a-container-on-a-mac-resolve-in-libgl-error-no-matching-fbconfigs-or-visuals-found

I don't know if linking other sites here is allowed, hope I'm not breaking any rules.

**Comment by Alex313031** [comment]
@tomobs I don't have a Mac to build. @midzer uses his Mac to make the Thorium releases, but IDK if he would be up for building Mercury for MacOS as well.

**Comment by j03ll0b0** [comment]
> @tomobs I don't have a Mac to build. @midzer uses his Mac to make the Thorium releases, but IDK if he would be up for building Mercury for MacOS as well.

well... I do have a Mac, not really, it's a EliteBook 840 G5, and a i9 12900K inn spain I handle remotely, the laptop is mine, but I don´t think my friend in spain would mind at all.

some test:
![Speedometer2 1-mercury](https://github.com/Alex313031/Mercury/assets/104862685/42b4ce39-78a5-474c-a2c8-b6ee913e3854)
![Speedometer2 1-thorium](https://github.com/Alex313031/Mercury/assets/104862685/f60ea553-a1bb-45ba-a272-1df89522e1bb)
![JetStream-mercury](https://github.com/Alex313031/Mercury/assets/104862685/3550f687-af6c-4164-88f1-d6ae6b49d04d)
![JetStream-thorium](https://github.com/Alex313031/Mercury/assets/104862685/196f0117-8ef4-4d68-a72d-a29830577656)
![MotionMark1 3-mercury](https://github.com/Alex313031/Mercury/assets/104862685/abef8088-3084-43e4-93ac-789a9096882a)
![MotionMark1 3-thorium](https://github.com/Alex313031/Mercury/assets/104862685/ae68f3f9-495b-4e4b-8454-dcc3b6108889)

thorium rocks!
and mercury is awesome too!

**Comment by j03ll0b0** [comment]
@Alex313031 I should say I would love to build for the mac, my specs:
![Screenshot 2024-01-16 at 5 07 54 AM](https://github.com/Alex313031/Mercury/assets/104862685/ee8c8595-2a35-4b3f-968e-fe51613d6ef5)

**Comment by j03ll0b0** [comment]
![Screenshot 2024-01-16 at 5 07 54 AM](https://github.com/Alex313031/Mercury/assets/104862685/9256115a-e494-42e4-a51f-c5fbc7018201)

**Comment by tomobs** [comment]
Got it, thanks!!!!! I love your project!

**Comment by Alex313031** [comment]
@j03ll0b0 @tomobs One could compile it on the hackintosh in spain.

**Comment by tomobs** [comment]
Okay...

**Comment by j03ll0b0** [comment]
Yay of course, where do I start?

**Comment by Alex313031** [comment]
@j03ll0b0 Lets talk somewhere else where I can guide you through how to compile it.

Note that you will need 100GB of free space, at least 8GB of RAM, and the more cores your CPU has, the better.

**Comment by j03ll0b0** [comment]
> @j03ll0b0 Lets talk somewhere else where I can guide you through how to compile it.
> 
> Note that you will need 100GB of free space, at least 8GB of RAM, and the more cores your CPU has, the better.

+584123685032 WhatsApp
nestor.espinoza.585 Facebook Messenger

**Comment by Alex313031** [comment]
@j03ll0b0 OK I messaged you on fb messenger

**Comment by j03ll0b0** [comment]
➜  mozilla-unified ./mach build

 0:00.64 W Clobber not needed.
 Config object not found by mach.
 0:00.80 Using Python 3.11.7 from /Users/juandeux/.mozbuild/srcdirs/mozilla-unified-7e22d0d3d1a8/_virtualenvs/build/bin/python
 0:00.81 checking for vcs source checkout... hg
 0:00.84 checking for a shell... /bin/sh
 0:01.11 checking for host system type... x86_64-apple-darwin23.3.0
 0:01.11 checking for target system type... x86_64-apple-darwin23.3.0
 0:01.34 checking whether cross compiling... no
 0:01.41 checking for the target C compiler... /usr/bin/clang
 0:01.41 checking for ccache... not found
 0:01.42 Using target sysroot in /Users/juandeux/.mozbuild/MacOSX14.0.sdk
 0:01.65 checking whether the target C compiler can be used... yes
 0:01.65 checking for the target C++ compiler... /usr/bin/clang++
 0:29.64 checking whether the target C++ compiler can be used... yes
 0:29.74 checking for unwind.h... yes
 0:32.68 checking for target linker...
 0:32.68 DEBUG: Executing: `/usr/bin/clang -isysroot /Users/juandeux/.mozbuild/MacOSX14.0.sdk -mmacosx-version-min=10.15 -std=gnu99 -Wl,--version`
 0:32.68 ERROR: Failed to find an adequate linker
*** Fix above errors and then restart with "./mach build"
➜  mozilla-unified

@tomobs we kinda hit a dead end last night but because there is a bug in Release, Nightly built just fine in vanilla taste, getting closer...

**Comment by Alex313031** [comment]
@j03ll0b0 I filed the bug. If they don't get back to us, we could always just wait until the release branch is at the same version as what is currently the nightly branch.
