### ISSUE TITLE
amd64 deb and zip are switched for release 121.0.1.

### ISSUE THREAD

**Issue by xiota** [Alex313031/Mercury#91]
The amd64 deb and zip are switched for release 121.0.1.  The sse versions are okay.

```
$ mimetype -M *121.0.1*
mercury-browser_121.0.1_SSE3.deb:  application/vnd.debian.binary-package
mercury-browser_121.0.1_amd64.deb: application/zip
mercury_121.0.1_linux_SSE3.zip:    application/zip
mercury_121.0.1_linux_x64.zip:     application/vnd.debian.binary-package

$ sha256sum *121.0.1*
f6d848decd5ae459c48a637578542b54de669ee0e1a699d53e98ef2903a4c38f  mercury-browser_121.0.1_SSE3.deb
c6fc654a70cc534e75902a472ea0a7f6346bcae31cac7f259d064d2b2293ee91  mercury-browser_121.0.1_amd64.deb
a792753a98c893a0df80bb14c113e3b27b70b25ed995f9486ba841c06430d413  mercury_121.0.1_linux_SSE3.zip
11e254891aea054ab6587553bc54220f97f31cb5036b821537ee044dea8c3913  mercury_121.0.1_linux_x64.zip
```

**Comment by Alex313031** [comment]
@xiota UGHHH. THANK YOU.

**Comment by Alex313031** [comment]
@xiota UPDATE: Corrected.

Also, you need to update the thorium-sse2-bin aur package you maintain.

x86-64-v2 requires SSE4.1 and SSE4.2 support > https://en.wikipedia.org/wiki/X86-64#Microarchitecture_levels

Therefore, this package will not install on many systems that could otherwise run it.

Instead, you should have it check explicitly for SSE3 support. An idea for how to do that can be found in my check_simd.sh script in the repo > https://github.com/Alex313031/thorium/blob/main/check_simd.sh

**Comment by xiota** [comment]
The scripts print advisory notices only.  They do not prevent the programs from continuing to run.  I would rather tell the user it won't work, but have it work anyway, because in this case, most users will ignore or never even see the message.  But if I tell the user it will work and it doesn't, they will come back to complain that it doesn't work.

So before updating the scripts, I would appreciate if you would point me to the specific config files used for each build.  In the Thorium-SSE3 repo, I see files named sandybridge and tigerlake, which both support SSE4.x.

I'm also curious about why you chose some intermediate state between v1 and v2 instead of full v2.

**Comment by Alex313031** [comment]
@xiota All those repos no longer host any source code. I need to delete those files. All source code for all platforms and architectures is now in the main repo > https://github.com/Alex313031/thorium

As for why, because SSE3 is Chromium's baseline, and there are quite alot of CPUs that support SSE3 but not SSE4.2. For example 1st gen opteron and athlon, pentium 4 prescott, pentium D, pentium M, and core 2 duo.

IMO x86-64-v2 should have been set at SSE4.1 not SSE4.2, since SSE4.2 was only introduced with 1st gen core, and even then, the lower end pentiums and celerons lacked it.

**Comment by xiota** [comment]
I'll update the scripts.  Does this also apply to `mercury-browser-sse3-bin`?

If the supported instruction sets change in a future build, please @ me.

**Comment by xiota** [comment]
Closing because confirmed files are fixed now:
```
$ mimetype -M *121*
mercury-browser_121.0.1_SSE3.deb:  application/vnd.debian.binary-package
mercury-browser_121.0.1_amd64.deb: application/vnd.debian.binary-package
mercury_121.0.1_linux_SSE3.zip:    application/zip
mercury_121.0.1_linux_x64.zip:     application/zip
```
